# Generated by Django 5.2.13 on 2026-04-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_trainer_session_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookIdempotency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('body_sha256', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='api.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
